### ISSUE TITLE
SM3运算结果和协议不一致（不是#define ROTL的那个问题）

### ISSUE THREAD

**Issue by Genevieve-Wei** [NEWPLAN/SMx#13]
SM3/Linux/sm3.c第198行：
for (j = 16; j < 64; j++)
    {
        SS1 = ROTL((ROTL(A, 12) + E + ROTL(T[j], j)), 7);
        ................
SS1这行ROTL(T[j], j)这里好像和协议不太符合，协议上左移位数是jmod32，是要取模运算的，j>31之后不能直接取j吧？

**Comment by HLinag** [comment]
不是以上问题，代码没有问题，知识 32 位的程序移植到64位上而产生的问题，直接将源代码中的long数据类型数据替换成 int 就行了，

**Comment by Genevieve-Wei** [comment]
> 不是以上问题，代码没有问题，知识 32 位的程序移植到64位上而产生的问题，直接将源代码中的long数据类型数据替换成 int 就行了，

**Comment by Genevieve-Wei** [comment]
> 

我明白了，谢谢~
