### ISSUE TITLE
sm4_crypt_cbc加解密结果不对

### ISSUE THREAD

**Issue by xiangweishan** [NEWPLAN/SMx#9]
您好，我使用例子中的sm4_crypt_ecb可以正常进行加解密，加密后进行解密可以得到原文。但是使用sm4_crypt_cbc就无法正常进行解密，解密出来的结果跟原文不一致。测试代码如下：
void Test1()
{
	unsigned char key[16] = { 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10 };
	unsigned char iv[16] = { 0x11, 0x33, 0x46, 0x69, 0x29, 0xac, 0xad, 0xdf, 0xfa, 0xfc, 0xab, 0x98, 0x76, 0x54, 0x32, 0x10 };
	unsigned char input[16] = { 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10 };
	unsigned char output[16];
	sm4_context ctx;
	unsigned long i;

	//encrypt standard testing vector
	sm4_setkey_enc(&ctx, key);
	sm4_crypt_cbc(&ctx, 1, 16, iv,input, output);
	for (i = 0; i < 16; i++)
		printf("%02x ", output[i]);
	printf("\n");

	//decrypt testing
	sm4_setkey_dec(&ctx, key);
	sm4_crypt_cbc(&ctx, 0, 16, iv,output, output);
	for (i = 0; i < 16; i++)
		printf("%02x ", output[i]);
	printf("\n");
}

**Comment by xiangweishan** [comment]
已解决

**Comment by tonyonce2017** [comment]
> 已解决

怎么解决的?我也是到这个问题

**Comment by tonyonce2017** [comment]
> > 已解决
> 
> 怎么解决的?我也是到这个问题

嗯...我试着把第一步加密的结果复制出来放到input里面, 然后把加密过程注释掉, 直接使用解密, 参数output, output改成input, ouput解密结果正确了, 估计是直接用第一步的加密结果作为参数出了什么问题

**Comment by tonyonce2017** [comment]
是因为第一步的加密结果output数组存的数据并不是16进制数据

**Comment by xiangweishan** [comment]
> 是因为第一步的加密结果output数组存的数据并不是16进制数据

调用sm4_setkey_enc后，key值发生了变化导致第二次调用sm4_setkey_dec时，由于key值与加密的key值不一致，导致解密结果不对
